api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_docs: true
    enable_entrypoint: false
    show_webby: false
    defaults:
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
